services:
  orthanc-pacs:
    image: lambki/danaul-orthanc-pacs:latest
    container_name: danaul-pacs
    build: ./orthanc-pacs
    depends_on: [index-db]
    restart: unless-stopped
    ports: ["4245:4242", "8042:8042"]
    volumes:
      - pacs-storage:/var/lib/orthanc/db
      - ./orthanc-pacs/plugins/euckr_to_utf8.py:/etc/orthanc/euckr_to_utf8.py:ro
      - ./orthanc-pacs/plugins/import_folder.py:/etc/orthanc/import_folder.py:ro
      - ./import:/import:ro
    environment:
      VERBOSE_ENABLED: "true"

      # OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      # DICOM_WEB_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"

      ORTHANC__POSTGRESQL__PASSWORD: "pg-password"
      ORTHANC__POSTGRESQL__HOST: "index-db"

  index-db:
    image: postgres:18
    container_name: pacs-index
    restart: unless-stopped
    ports: ["5438:5438"]
    volumes: ["index-storage:/var/lib/postgresql"]
    environment:
      POSTGRES_PASSWORD: "pg-password"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  dicom-importer:
    image: lambki/danaul-dicom-importer:latest
    build: ./dicom-importer
    container_name: dicom-importer
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - orthanc-pacs
    environment:
      ORTHANC_URL: "http://orthanc-pacs:8042"
      ORTHANC_USER: "demo"
      ORTHANC_PASSWORD: "demo"

volumes:
  pacs-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./orthanc-pacs/pacs-storage
  index-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./orthanc-pacs/index-storage
